name: radicale
version: '2.1.8'
summary: Unofficial snap for radicale
description: |
  Radicale is a lightweight CalDAV and CardDAV solution with support for
  multiple calendars and address books.

grade: devel
confinement: devmode

apps:
  radicale:
    command: radicale --config "" --storage-filesystem-folder=$SNAP_COMMON/storage

parts:
  radicale:
    source: https://github.com/Kozea/Radicale/archive/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: python
    python-version: python3
