name: radicale-dfialho
version: '2.1.8'
summary: Unofficial snap for radicale
description: |
  Radicale is a lightweight CalDAV and CardDAV solution with support for
  multiple calendars and address books.

grade: devel
confinement: strict

apps:
  radicale:
    command: bin/wrapper.sh
    daemon: forking
    restart-condition: always
    stop-timeout: 20s
    plugs:
      - network-bind

  users:
    command: bin/users.sh

  enable-https:
    command: bin/enable-https.sh
    plugs:
      - network

  disable-https:
    command: bin/disable-https.sh

  renew-certs:
    command: bin/renew-certs.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network

parts:
  radicale:
    source: https://github.com/Kozea/Radicale/archive/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: python
    python-version: python3
    python-packages:
      - passlib
      - bcrypt

  wrapper:
    plugin: dump
    source: files/
    prepare: |
      chmod +x bin/wrapper.sh
      chmod +x bin/users.sh
      chmod +x bin/enable-https.sh
      chmod +x bin/disable-https.sh
      chmod +x bin/renew-certs.sh

  htpasswd:
    plugin: nil
    stage-packages:
      - apache2-utils

  git:
    plugin: nil
    stage-packages:
      - git

  certbot:
    source: https://github.com/certbot/certbot/archive/v0.21.1.tar.gz
    plugin: python
    python-version: python2
    build-packages: 
      - python-dev
      - libffi-dev
      - gcc
      - libssl-dev
