#!/bin/sh
set -e

. $SNAP/defs.sh

# Make sure the user files exists
touch $USERS_FILE
# Prevent other users other than root from reading the users file
chmod 600 $USERS_FILE

##
# Logging
##

# Create loggers file from template
cp $SNAP/loggers.template $LOGGERS_FILE

# Set path to log file
sed -i -e "s%\%(LOGFILE)%$LOG_FILE%g" $LOGGERS_FILE

# Create the storage directory
mkdir $STORAGE_DIR/

snapctl set port=5232
